export { default as ImgIcon } from './ImgIcon'
export { default as TabItem } from './TabItem'
export * from './Seperators'
export { default as CText } from './TextComp'
export { default as EmptyComponent } from './EmptyComponent'
export { default as FullScreenLoader } from './FullScreenLoader'
export { default as Loader } from './Loader'
export { default as ImgBadge } from './ImgBadge'
export { default as IconComp } from './IconComp'
export { default as ImgOrText } from './ImgOrText'
export { default as TopTabsBar } from './TopTabsBar'

//New Components
export { default as SectionHeader} from './SectionHeader'
export { default as RatingsComp} from './RatingsComp'
export { default as ReviewsSummary} from './ReviewsSummary'
export { default as RatingStar } from './RatingStar'
export { default as TapRating } from './TapRating'
export { default as ReviewCard } from './ReviewCard'
export {default as HospitalCard} from './HospitalCard'
